name:
    gpt

channels:
    - pytorch
    - conda-forge

dependencies:
    - python=3.9
    - pip
    - black
    - numpy
    - scipy
    - tqdm
    - matplotlib
    - seaborn
    - pytorch
    - ipykernel
    - ipywidgets>=7.0,<8.0
    - jupyter
    - pip:
      - pydove
